name: CI

on: 
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20.5.1'
      
      - run: npm install

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo apt-get install -y docker-compose

      - run: docker-compose up --build -d

      - run: sleep 10 

      - run: npm run test:api

      - run: npm run testAllContract
      
      - run: docker-compose down
